### PR TITLE
added information about kie 7.3.x, uberfire 1.3.x and dashbuilder 0.9…

### PR DESCRIPTION
**Pull request by mbiarnes**
….x branches

### CODE REVIEW

**Comment by mbiarnes** [comment]
@psiroky please review this

**Comment by mbiarnes** [comment]
@psiroky seems the scripts doesn'r like the same notation 0.9.x for uberfire in kie 6.5.x and dashbuilder in kie 7.3.x

**Comment by mcimbora** [comment]
Proposed fix: https://github.com/kiegroup/kie-build-helper-jenkins-plugin/pull/5

**Comment by mbiarnes** [comment]
will close this PR

**Pull request closed without merging**
